# Generated by Django 5.2.15 on 2026-07-02 21:23

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('nombre', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('forraje', 'Forraje'), ('concentrado', 'Concentrado'), ('suplemento', 'Suplemento')], max_length=20)),
                ('stock_actual', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('stock_minimo', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('costo_unitario', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('fecha_ultima_entrada', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Alimento',
                'verbose_name_plural': 'Alimentos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('rfid_tag', models.CharField(max_length=100, unique=True, verbose_name='Tag RFID')),
                ('numero_interno', models.CharField(max_length=50, verbose_name='Número interno')),
                ('especie', models.CharField(choices=[('bovino', 'Bovino'), ('otro', 'Otro')], default='bovino', max_length=20)),
                ('raza', models.CharField(blank=True, max_length=100)),
                ('sexo', models.CharField(choices=[('macho', 'Macho'), ('hembra', 'Hembra')], max_length=10)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('peso_actual', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('vendido', 'Vendido'), ('muerto', 'Muerto'), ('cuarentena', 'Cuarentena')], default='activo', max_length=20)),
                ('fecha_registro', models.DateField(default=django.utils.timezone.localdate)),
            ],
            options={
                'verbose_name': 'Animal',
                'verbose_name_plural': 'Animales',
                'ordering': ['numero_interno'],
            },
        ),
        migrations.CreateModel(
            name='LecturaRFID',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('rfid_tag_leido', models.CharField(max_length=100)),
                ('fecha_hora', models.DateTimeField(default=django.utils.timezone.now)),
                ('ubicacion_texto', models.CharField(blank=True, max_length=500)),
                ('procesado', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Lectura RFID',
                'verbose_name_plural': 'Lecturas RFID',
                'ordering': ['-fecha_hora'],
            },
        ),
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('nombre', models.CharField(max_length=200)),
                ('capacidad', models.PositiveIntegerField(help_text='Capacidad máxima de animales')),
                ('ubicacion', models.CharField(blank=True, max_length=500)),
            ],
            options={
                'verbose_name': 'Lote / Potrero',
                'verbose_name_plural': 'Lotes / Potreros',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='MovimientoAlimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('tipo', models.CharField(choices=[('entrada', 'Entrada'), ('consumo', 'Consumo')], max_length=10)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fecha', models.DateField(default=django.utils.timezone.localdate)),
                ('notas', models.CharField(blank=True, max_length=500)),
            ],
            options={
                'verbose_name': 'Movimiento de alimento',
                'verbose_name_plural': 'Movimientos de alimento',
                'ordering': ['-fecha', '-created'],
            },
        ),
        migrations.CreateModel(
            name='EventoAnimal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('tipo', models.CharField(choices=[('vacunacion', 'Vacunación'), ('enfermedad', 'Enfermedad'), ('tratamiento', 'Tratamiento'), ('parto', 'Parto'), ('inseminacion', 'Inseminación'), ('venta', 'Venta'), ('traslado', 'Traslado'), ('muerte', 'Muerte'), ('revision', 'Revisión'), ('pesaje', 'Pesaje')], max_length=20)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('descripcion', models.TextField(blank=True)),
                ('valor_numerico', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='ganado.animal')),
            ],
            options={
                'verbose_name': 'Evento de animal',
                'verbose_name_plural': 'Eventos de animales',
                'ordering': ['-fecha'],
            },
        ),
    ]
