# Generated by Django 5.2.15 on 2026-07-02 21:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ganado', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='eventoanimal',
            name='usuario_responsable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_ganado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lecturarfid',
            name='animal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lecturas_rfid', to='ganado.animal'),
        ),
        migrations.AddField(
            model_name='lote',
            name='tipo_alimento_actual',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lotes', to='ganado.alimento'),
        ),
        migrations.AddField(
            model_name='lecturarfid',
            name='ubicacion_lote',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lecturas_rfid', to='ganado.lote'),
        ),
        migrations.AddField(
            model_name='animal',
            name='lote',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='animales', to='ganado.lote'),
        ),
        migrations.AddField(
            model_name='movimientoalimento',
            name='alimento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='ganado.alimento'),
        ),
    ]
