# Generated by Django 5.2.15 on 2026-07-02 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ganado', '0003_animal_foto_proxima_revision_evento_severidad'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='animal',
            new_name='ganado_anim_estado_a5c51f_idx',
            old_name='ganado_anim_estado_idx',
        ),
        migrations.RenameIndex(
            model_name='animal',
            new_name='ganado_anim_lote_id_661562_idx',
            old_name='ganado_anim_lote_estado_idx',
        ),
    ]
